### ISSUE TITLE
Add proper handling of masterless mods

### ISSUE THREAD

**Issue by slowpard** [slowpard/slowLODGen#5]

**Comment by slowpard** [comment]
```
2024-10-18 17:39:28,915 - INFO - Oblivion path: c:\gog games\oblivion\data
2024-10-18 17:39:28,915 - INFO - plugins.txt path: C:\Users\GBR\AppData\Local\Oblivion\plugins.txt
2024-10-18 17:39:28,917 - INFO - ['MergedLOD.esm', 'Oblivion.esm', 'DLCBattlehornCastle.esp', 'DLCMehrunesRazor.esp', 'DLCFrostcrag.esp', 'DLCHorseArmor.esp', 'Knights.esp', 'DLCOrrery.esp', 'DLCSpellTomes.esp', 'DLCShiveringIsles.esp', 'DLCThievesDen.esp', 'DLCVileLair.esp']
2024-10-18 17:39:28,917 - INFO - Reading: MergedLOD.esm
2024-10-18 17:39:28,917 - INFO - Reading: Oblivion.esm
Traceback (most recent call last):
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 2064, in <module>
    parser.renumber_formids(master_map)
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 1849, in renumber_formids
    record.renumber_formids(formid_chg_map, self.formid_map)
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 1758, in renumber_formids
    record.renumber_formids(formid_chg_map, formid_map)
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 1758, in renumber_formids
    record.renumber_formids(formid_chg_map, formid_map)
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 1758, in renumber_formids
    record.renumber_formids(formid_chg_map, formid_map)
  [Previous line repeated 2 more times]
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 1658, in renumber_formids
    super().renumber_formids(formid_chg_map, formid_map)
  File "C:\Users\GBR\Desktop\slowLODGen-main\slowLODGen.py", line 1607, in renumber_formids
    if formid_chg_map[mod_id] != mod_id:
       ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 1
```
